---
#
# OSRM
#
#
- name: download country data file .osm.pbf
  get_url: url=http://download.geofabrik.de/europe/great-britain/{{data_country_name}}-latest.osm.pbf dest=/home/osrm/{{data_country_name}}-latest.osm.pbf force=no mode=0644

- name: extract
  shell:
    osrm-extract -p /usr/local/src/osrm/profiles/car.lua /home/osrm/{{data_country_name}}-latest.osm.pbf
    chdir={{osrm_datadir}}

- name: contract
  shell:
    osrm-contract /home/osrm/{{data_country_name}}-latest.osrm
    chdir={{osrm_datadir}}

- name: configure systemd
  template: >
    src="osrm.service"
    dest="/etc/systemd/system/osrm.service"
    mode=0644

- name: enable OSRM service
  shell:
    systemctl enable osrm
