---
# Sample playbook
#
# Use on ec2 with Ubutun
#
# Usage:
#   ansible-playbook ./ec2-ubuntu.yml -u ubuntu -i "ec2-42-42-42-42.compute-1.amazonaws.com,"
#
- hosts: localhost
  sudo: True
  gather_facts: False
  roles:
    - osrm
    - osrm-data
